### ISSUE TITLE
[FBref] Cannot deal with pre-1900 seasons

### ISSUE THREAD

**Issue by probberechts** [probberechts/soccerdata#115]
Fbref added pre-1900 seasons for the English first division (see https://fbref.com/en/comps/9/history/Premier-League-Seasons). The FBref scraper cannot deal with this and crashes while scraping Premier League data.

**Comment by jayhaytch** [comment]
Has this been solved already? I wanted to exercise a bit trying to solve it but I can't really recreate the crash. There is a duplicate problem due to the fact that the season_code function shrinks the season-pair to a format where there are duplicates but overall it kind of works. Of course it crashes when trying to scrape stats before 1992-1993 but thats because there actually are no stats to scrape so I don't think this was the problem?

Regarding the duplicates problem, the only solution I see is changing the season_code function and creating a new code with the full first season and the last two values of the second season (or the last 3 of the first season and the last 2 of the second season but it seems confusing to me)

2022-23 => 202223
1922-23 => 192223

But this means that everyone trying to scrape stuff using 

```
pat2 = re.compile(r"^[0-9]{2}$")  # 94
pat6 = re.compile(r"^[0-9]{2}-[0-9]{2}$")  # 94-95
```

this two patterns would see their code crash. Although it would be quite an easy fix with the correct error. I would be happy to try and do it if you like the idea!
