### ISSUE TITLE
[WhoScored] javascript undefined args when fetching data

### ISSUE THREAD

**Issue by alexbarnsley** [probberechts/soccerdata#633]
When fetching the data from whoscored.com, I've started receiving the below error. Upon a little investigation, it seems the `var` path has been changed _again_ (based on the recent PR #618)

```
selenium.common.exceptions.JavascriptException: Message: javascript error: Cannot read properties of undefined (reading 'args')
```

As you can see in the screenshot below, the formatting seems to have changed compared to what is being looked for, and I've not been around long enough to know what the correct data should look like?:

![image](https://github.com/probberechts/soccerdata/assets/8069294/a3f101b9-bc07-48f3-b152-72d0fb03ffa2)

In case it's relevant only for a specific match, it's occurring on `/Matches/1245647/Live`

Versions:

**soccerdata**: 1.8.1
**selenium**: 4.22.0
**undetected-chromedriver**: 3.5.5

P.S. Great work with this library!

Thanks,

Alex

**Comment by probberechts** [comment]
There is no event data for the game you are referring to. You can see this because there is no widget with the line-ups, chalkboard, etc. under the "Match Centre" tab.

 It seems that I forgot to update the error-handling logic in #618. I assume there will be no issues for games for which event data is available.

**Comment by alexbarnsley** [comment]
That's good to know. I tested using the branch/PR and it all seems to be working without issues now, thanks!
